// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5BC1yf_meE-Osm6BCyYLIraumRsXb9EI',
    appId: '1:32462513958:web:bd612304573ffa9694c3e7',
    messagingSenderId: '32462513958',
    projectId: 'algohub-9ee7f',
    authDomain: 'algohub-9ee7f.firebaseapp.com',
    storageBucket: 'algohub-9ee7f.firebasestorage.app',
    measurementId: 'G-MXBZRGKDWW',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRN3KtVEmaQljCdfucePaNB8JfZLRSgi8',
    appId: '1:32462513958:android:d2cc9bfd036737be94c3e7',
    messagingSenderId: '32462513958',
    projectId: 'algohub-9ee7f',
    storageBucket: 'algohub-9ee7f.firebasestorage.app',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5BC1yf_meE-Osm6BCyYLIraumRsXb9EI',
    appId: '1:32462513958:web:6a801ae304b66a7794c3e7',
    messagingSenderId: '32462513958',
    projectId: 'algohub-9ee7f',
    authDomain: 'algohub-9ee7f.firebaseapp.com',
    storageBucket: 'algohub-9ee7f.firebasestorage.app',
    measurementId: 'G-RPPK4FFPP9',
  );
}